services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo_database
    environment:
      MONGO_INITDB_DATABASE: mongo_database
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"
